### PR TITLE
Fix handling of file targets

### PR DESCRIPTION
**Pull request by krlmlr**
and some minor cleanup.

### CODE REVIEW

**Comment by krlmlr** [comment]
This requires exporting a symbol from remake, I'm working on a pull request.

**Comment by krlmlr** [comment]
Works with current remake.

**Comment by krlmlr** [comment]
@wlandau: Do you have comments regarding this PR? I don't quite like how subdirectories for the shadow targets are created, but I'm not sure how to improve.

**Comment by wlandau** [comment]
I'm not sure when I'll have time, but I will have a look. Thank you for fixing the tests.

**Comment by wlandau** [comment]
Thanks, @krlmlr! All your changes look great, and it looks like remakeGenerator likes the updates too. I did not know that file targets were an issue, and that part of remake is still a bit unclear to me. Sorry it took me so long to get back to you. 

By the way: in a commit message, you mentioned `PARALLEL_REMAKE_RUNNER="bsub -K" make` for LSF. Are you using that as a `prepend` line?

**Comment by krlmlr** [comment]
The `PARALLEL_REMAKE_RUNNER="bsub -K" make` construct sets the `PARALLEL_REMAKE_RUNNER` environment variable for the `make` process only. With our `Makefile`, `bsub -K` is prepended to each command. (`bsub -I` also works, that command also shows the process's output.)

I wonder if we also could specify an alternative shell in the `Makefile`.

**Comment by krlmlr** [comment]
Look for `SHELL` in the [specs](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html).

**Comment by wlandau** [comment]
Actually, `SHELL` happens to be the [primary intended use case for `prepend`](http://will-landau.com/parallelRemake/articles/parallelRemake.html#high-performance-computing). When I was in grad school, I used `SHELL=srun` to [distribute targets over SLURM jobs](http://plindenbaum.blogspot.com/2014/09/parallelizing-gnu-make-4-in-slurm.html). Now I'm using the Univa Grid Engine, and `SHELL=./shell.sh` seems to do the trick if `shell.sh` is 

```r
#!/bin/bash
shift
echo "module load R; $*" | qsub -sync y -cwd -j y
```

**Comment by krlmlr** [comment]
That's what I thought too. So, can you actually run `SHELL="bsub -I" make` ? Or does it need to be a single command? Anyway, we probably can revert b5fa81b.

Can we define a universal build rule?

```
.makefile/%:
        R -q -e 'parallelRemake:::process("$<")`
```

**Comment by wlandau** [comment]
I think `prepend = c("SHELL=bsub", ".SHELLFLAGS=-I")` could work. If it works for you, I'll go ahead and revert https://github.com/wlandau/parallelRemake/commit/b5fa81b61d25a0505054da1333c22b960f2d84e4.

I do like the idea of a universal build rule. That could shorten the Makefile dramatically. I'm not very good at those though, and I haven't figured out how to do that in a way that lays out the dependency tree correctly.

**Comment by krlmlr** [comment]
436a959 is a prerequisite, this uses one line per dependency and also a separate line for the rule. I think we could just replace the code that starts at https://github.com/wlandau/parallelRemake/commit/436a95947f3aa36b3f24cba73a66c82462531d10#diff-85c242353aa117b9e553328203dd05eeR26 with one universal build rule. (What about knitr rules?)

**Comment by wlandau** [comment]
What needs to be done differently for knitr rules? (I think I'm missing something here, I thought remake handled that special case.)

Also, is there a particular reason why you chose

```r
all: target1
all: target2
```

rather than 

```
all: \
target1 \
target2
```

I'm using the second option for [drake](https://github.com/wlandau-lilly/drake), and it seems to work on Red Had, Windows 7, and Mac OS 10.12.3.

**Comment by krlmlr** [comment]
No idea about knitr rules. I chose the first option to minimize VCS diffs when the workflow changes.

**Comment by wlandau** [comment]
Ah, I see. As long as both options are equally portable, it's a fine distinction with minor tradeoffs. I do not plan to take action on the backslashes or lack thereof at this point.

**Pull request merged**
